CREATE DATABASE BANCOHUE

GO
USE BANCOHUE

CREATE TABLE CLIENTE (
CPF CHAR (11) NOT NULL UNIQUE CHECK(LEN(CPF) = 11),
NOME VARCHAR (200) NOT NULL,
AGENCIA CHAR (4) NOT NULL,
CONTA VARCHAR (10) NOT NULL,
SALDO DECIMAL (10,2) NOT NULL,
PRIMARY KEY(CPF)
)

CREATE TABLE LOGIN(
LOGIN NVARCHAR (50) UNIQUE NOT NULL,
SENHA NVARCHAR (30) NOT NULL,
CPF CHAR (11) NOT NULL,
PRIMARY KEY (LOGIN),
FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF)
)

CREATE TABLE EXTRATO  (
DATAOCORRENCIA DATETIME NOT NULL,
OCORRENCIA VARCHAR (100) NOT NULL,
DESCRICAO VARCHAR (200) NULL,
VALOR DECIMAL (10,2) NOT NULL,
AGENCIA CHAR (4) NOT NULL,
CONTA VARCHAR (10) NOT NULL,
CPF CHAR (11) NOT NULL,
FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF)
)